lib/teacher_web/router.ex
defmodule TeacherWeb.Router do
  use TeacherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TeacherWeb do
    pipe_through :browser

    resources "/sessions", SessionController, only: [:new, :create]
    delete "/sign-out", SessionController, :delete
    resources "/registrations", RegistrationController, only: [:new, :create]

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TeacherWeb do
  #   pipe_through :api
  # end
end

lib/teacher/application.ex
defmodule Teacher.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Teacher.Repo,
      # Start the endpoint when the application starts
      TeacherWeb.Endpoint
      # Starts a worker by calling: Teacher.Worker.start_link(arg)
      # {Teacher.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Teacher.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TeacherWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/teacher/repo.ex
defmodule Teacher.Repo do
  use Ecto.Repo,
    otp_app: :teacher,
    adapter: Ecto.Adapters.Postgres
end

lib/teacher_web/controllers/page_controller.ex
defmodule TeacherWeb.PageController do
  use TeacherWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/teacher_web/controllers/registration_controller.ex
defmodule TeacherWeb.RegistrationController do
  use TeacherWeb, :controller

  alias Teacher.Auth

  def new(conn, _params) do
    render conn, "new.html", changeset: conn
  end

  def create(conn, %{"registration" => registration_params}) do
    case Auth.create_user(registration_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You have successfully signed up")
        |> redirect(to: Routes.page_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

end

lib/teacher_web/controllers/session_controller.ex
defmodule TeacherWeb.SessionController do
  use TeacherWeb, :controller

  alias Teacher.Auth

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => %{"email" => email, "password" => password}}) do
    case Auth.sign_in(email, password) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You have signed in successfully :)")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, _reason} ->
        conn
        |> put_flash(:error, "Invalid Email or Password")
        |> render("new.html")
    end
  end

  def delete(conn, _params) do
    conn
    |> delete_session(:current_user_id)
    |> put_flash(:error, "You have signed out")
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/teacher_web/views/error_view.ex
defmodule TeacherWeb.ErrorView do
  use TeacherWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/teacher_web/views/layout_view.ex
defmodule TeacherWeb.LayoutView do
  use TeacherWeb, :view
end

lib/teacher_web/views/page_view.ex
defmodule TeacherWeb.PageView do
  use TeacherWeb, :view
end

lib/teacher_web/views/registration_view.ex
defmodule TeacherWeb.RegistrationView do
  use TeacherWeb, :view

end

lib/teacher_web/views/session_view.ex
defmodule TeacherWeb.SessionView do
  use TeacherWeb, :view

end

lib/teacher_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Teacher · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <main role="main" class="container">
      <%= if Teacher.Auth.user_signed_in?(@conn) do %>
        <%= link "Sign out", to: Routes.session_path(@conn, :delete), method: :delete %>
      <% else %>
        <%= link "Sign in", to: Routes.session_path(@conn, :new) %> |
        <%= link "Sign up", to: Routes.registration_path(@conn, :new) %>
      <% end %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/teacher_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed and maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

lib/teacher_web/templates/session/new.html.eex
<h2>Sign in</h2>
<%= form_for @conn, Routes.session_path(@conn, :create), [as: :session], fn f -> %>
  <%= label f, :email, "Email address" %>
  <%= text_input f, :email, required: true, autofocus: true %>
  <br>
  <%= label f, :password %>
  <%= password_input f, :password, required: true %>
  <br>
  <%= submit "Sign in" %>
<% end %>